version: 0.0
os: linux
files:
  - source: /
    destination: /opt/installer
hooks:
  ApplicationStop:
    - location: /opt/scripts/apacheinstall.sh
      timeout: 300
  BeforeInstall:
    - location: /opt/scripts/index.sh
      timeout: 300
  ApplicationStart:
    - location: /opt/scripts/verify.sh
      timeout: 300
  ValidateService:
    - location:  /opt/scripts/validate.sh
